# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 084463307fc10446a3fe07500e96e2fdcbde805ae36f1ae75385302c6dc75343d3037b341957bd0cb806dd7fe2c29397b577b061aaf6f8d4dae2ef68dab9ed5c

test:
  secret_key_base: a90a3d1f67e8d0b4846e2996acf3aa88e5094e28690652fa5edf825cdb04352f8055243c426c21af82510a15b433af537182587eb7e5f12942991b64ad994f83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
